### ISSUE TITLE
About the train.py

### ISSUE THREAD

**Issue by 571502680** [cvlab-epfl/segmentation-driven-pose#1]
When do you share train.py? the work is very good!

**Comment by YinlinHu** [comment]
Sorry, we can not provide the training codes according to the regulations from the funding partners. While I think there will soon be many alternative implementations based on this repository. Such as efforts from #2.

**Comment by sjtuytc** [comment]
I have implemented one.
See https://github.com/sjtuytc/segmentation-driven-pose.
