### ISSUE TITLE
How is data/YCB-Video/YCB_vertex.npy generated

### ISSUE THREAD

**Issue by renxinyang** [cvlab-epfl/segmentation-driven-pose#11]
Hi,
We are trying to render the point-cloud model to the 2D picture. The predicted 6Dpose worked fine with ply generated from YCB_vertex.npy but the result was strange with the ply file from the official website of YCB dataset. Could you explain how you generated YCB_vertex.npy? We have attached the screen shot of two ply files opened in meshlab and it can be seen that they are different. Thank you!
![Screenshot from 2019-10-15 18-08-37](https://user-images.githubusercontent.com/45685209/66822831-9e731680-ef77-11e9-8af9-f6ec4ca2fc8c.png)

**Comment by YinlinHu** [comment]
We just extract the vertex from the official YCB dataset and save them in YCB_vertex.npy for all the 21 objects. This procedure is trivial and just for visualization, yours should also work after some debugging.

**Comment by renxinyang** [comment]
Ok, thank you.

**Comment by madhumilan** [comment]
Hi,

Thanks for the explanation. Can you please also tell how to generate **data/YCB_bbox.npy**. As in, how the 8 points of the 3D bounding box is chosen from the .ply file? Thanks.

Best regards,
Madhu
