### ISSUE TITLE
Coordinate system convention of the ground truth poses

### ISSUE THREAD

**Issue by SelvamArul** [cvlab-epfl/segmentation-driven-pose#5]
Hi,
One more question related to original LineMOD. The ground truth poses in Occluded-LineMOD dataset follows the OpenGL Coordinate system convention (camera viewing direction is the negative Z-axis)  as mention in the section 2.2 of [this](https://hci.iwr.uni-heidelberg.de/vislearn/HTML/projects/scene_understanding/OcclusionDataset_ReadMe.pdf) document. But I am not sure of the coordinate system convention used in the original LineMOD dataset. For example one of the transformation file like looks like 
        `-13.0792` 
       `-7.83575`
        `104.177` 
 The values are in **centimetres**. 
so, that's ~1 meters along the _positive_ _z_-axis.
This make me think that the poses are annotated with [OpenCV](https://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html) 
coordinate system convention. But my rendering pipeline is not working correctly if I follow this assumption.  Any idea how the ground truth poses in original LineMOD dataset is defined?
Also, what this [file](https://github.com/cvlab-epfl/segmentation-driven-pose/blob/master/data/Occluded-LINEMOD/Transform_RT_to_OccLINEMOD_meshes.npy) in your repo is for?

Sorry that this issue is not about the segmentation-driven-pose repo but rather a general question.

**Comment by YinlinHu** [comment]
This do is a general confusing problem.
As there are many versions of LINEMOD dataset, we use the normalized one at: https://files.icg.tugraz.at/f/472f5d1108/
But as you may notice, the model used in Occ-LINEMOD (https://hci.iwr.uni-heidelberg.de/vislearn/iccv2015-occlusion-challenge/) is not the same as the above.
While, only a simple model transformation is enough, that is what the file you mentioned exactly do.

**Comment by SelvamArul** [comment]
Thanks a lot for your reply. I am using the normalized version of LINEMOD you shared and it works. BTW, where did you find the link for downloading normalized LINEMOD or any mention of it? The project [page](https://www.tugraz.at/institute/icg/research/team-lepetit/research-projects/object-detection-and-3d-pose-estimation/) from ICG deos not mention anything about it. As you said, there are many different versions of LINEMOD and I came across many projects here in github that use LINEMOD but none mentioned this version. Is there any paper that mention this version? I am sorry if I missed something obvious. Thanks again for your reply.

**Comment by YinlinHu** [comment]
We just got the dataset from the member of ICG, it obviously is a cleaned and refined version, but without any documents. While, which version you use is not that important, just make them consistent is enough, I think.

**Comment by SelvamArul** [comment]
Ya, sure. This normalized version is much cleaner. I will stick to this version.
