### ISSUE TITLE
No Fusion

### ISSUE THREAD

**Issue by taeyeopl** [cvlab-epfl/segmentation-driven-pose#8]
Thanks for the sharing the code.
I'm confused the word No Fusion and Oracle. Could you explain about it?? 

Supposed finding a cup 8 corner.

1. Is that right No Fusion means predict 8 corners only based on the object segmentation mask a center grid with not using confidence score and confidence loss
But the Fusion means predict 8 corners based on the object segmentation mask (included a center grid and other grids in mask) and using the highest confidence score and confidence loss?  

2. "In paper Oracle results obtained by selecting the best predicted 2D location for each 3D keypoints using the ground truth 2D reprojections.'
Could you explained detailed about how to selecting the best predicted 2D location?? Is that means selecting the closest location between predicted 2D keypoints and ground truth 2d projections??

3. Is that right oracle 3D keypoint means a cup's ground truth 8 corner points (3D bounding box)?

**Comment by YinlinHu** [comment]
The core difference between NF and Oracle is whether using the ground truth 2D reprojection.
The NF scheme just chooses the local prediction from the center grid without any fusion.
While the Oracle scheme makes the fusion procedure guided by the ground truth 2D reprojection. That is choosing the closest point to the GT positions for each keypoint from the cluster.

Keep in mind that, the Oracle scheme is not practical that, in a real situation, there is no GT during the test. This scheme is just a demonstration of the potential of our method. A better fusion strategy worth further research.

**Comment by taeyeopl** [comment]
Thanks for reply
